/*
Powered by ly200.com		http://www.ly200.com
广州联雅网络科技有限公司		020-83226791
*/

var lang_obj={
	global:{
		'add':'Add',
		'edit':'Edit',
		'submit':'Submit',
		'confirm':'Confirm',
		'cancel':'Cancel',
		'copy_confirm':'Enter the product replication mode, continue?',
		'copy_model_confirm':'Enter the attribute replication mode, continue?',
		'del_confirm':'Irretrievable after deletion, continue?',
		'reset_confirm':'Confirm to restore the default settings, continue?',
		'used_confirm':'Ready to turn on the batch mode, continue?',
		'close_confirm':'Ready to turn off the batch mode, continue?',
		'my_order_confirm':'Ready to turn on the sorting mode, continue?',
		'sold_in_confirm':'Ready to turn on the sales mode, continue?',
		'sold_out_confirm':'Ready to turn on the off sales model, continue?',
		'data_posting':'Data being submitted...',
		'loading':'Loading...',
		'sync':'Data being synchronization...',
		'confirm_password_error':'Login password does not match with the confirmed password, please re-enter!',
		'del_dat_select':'Please select the item to be deleted',
		'used_dat_select':'Please select the item to be started',
		'close_dat_select':'Please select the item to be closed',
		'dat_select':'Please select the chosen item',
		'correct_message':'Please fill in the correct data',
		'n_y':['No','Yes'],
		'open':'Unfold',
		'pack_up':'Fold',
		'del':'Delete',
		'picture':'Picture',
		'picture_name':'Picture Name',
		'set_error':'Setup failed unknown mistakes!'
	},
	format:{
		'mobilephone':'Please fill in the phone number correctly!',
		'telephone':'Please fill in the telephone number!',
		'fax':'Please fill in the fax number correctly!',
		'email':'Please fill in the email address correctly!',
		'length':'Incorrect length! You need to fill in %num% digits.'
	},
	signIn:{
		'title':'Sign In',
		'error_note':'Incorrect email address or password. Please try again.<br> Make sure the Caps Lock is off before you enter password.',
		'email':'Email',
		'password':'Password',
		'forgot':'Forgot your <a href="/account/forgot.html" class="forgot">password</a>?',
		'stay_note':'Stay signed in <span>Protect your privacy - sign out when you\'re done.</span>',
		'sign_in':'Sign in',
		'join_fee':'Join Free'
	},
	newsletter:{
		'success':'Added to subscribe successful!',
		'exists':'This mailbox already exists subscription!'
	},
	language:{
		'zh-cn':'Chinese',
		'en':'English ',
		'jp':'Japanese',
		'de':'German',
		'fr':'French',
		'es':'Spanish',
		'ru':'Russian',
		'pt':'Portuguese',
		'zh_tw':'Traditional Chinese'
	},
	manage:{
		frame:{
			'time':'Time',
			'status':'Status',
			'support':['Enterprise QQ', 'Working Hours', 'Telephone', 'We Chat', 'Superior Complainant', 'Website Expiration Time'],
			'data_backup':'Data Backup',
			'backup':['Database', 'Folder'],
			'file_upload':'SELECT FILES'
		},
		account:{
			"log_in":"The system is trying to log in, please wait...",
			"log_in_ok":"Successful login, the page jumps, please wait...",
			"order_quantity":"Website Order",
			"page_view":"Site Visits",
			"success_cache":"Cache has been cleared successfully!",
			"percentage":"Percentage",
			"picture_tips":"You have uploaded more than xxx pictures and cannot uploaded anymore!",
			"password_tips":"Re-password do not match, please re-enter!"
		},
		set:{
			"select_once_language":"Please select at least one language version",
			"print_0":"Print the customs declaration",
			"print_1":"Print invoice",
			"platform_ary":{'SignIn':'Login','Pixel':'Statistics'},
		},
		module:{
			"sure_module":"Are you sure to choose this style?",
			"name":"Name",
			"url":"Links address",
			"target":"New window",
		},
		counrtry:{
			"state":"Province",
		},
		photo:{
			"empty_temp":"Temporary folder has been cleared successfully!",
			"move_success":"Removed successfully",
			"picture_upload":"Picture Upload"
		},
		shipping:{
			"area_config":"Area Config",
		},
		products:{
			"category_tips":"Please select the product category",
			"qty":"Quantity",
			"price":"Price",
			"mark_up":"Price increased",
			"discount":"Discount",
			"group_attr":"Combination Properties",
			"wholesale_discount_notes":"The price of the product attribute selected by the current station is the unit price, the calculation of the wholesale price will be calculated in a discounted way",
			"prefix_tips":"The prefix of product number can’t be empty!",
			"sync_change_account":"Switching account..."
		},
		sales:{
			"seckill":"Seckilling",
			"promotion":"Promotion",
			"proName":"Product Name",
			"proPrice":"Product Price",
			"proNumber":"Product Number",
			"proBiref":"Brief introduction",
			"start_time":"Starting time",
			"duration":"Duration",
			"hour":"Hours",
			"tuan_price":"Group-buying price",
			"buyer_count":"Purchases",
			"total_count":"Restrictions",
			"promotion_price":"Total promotion price",
			"seckill_price":"Price spike",
			"qty":"Quantity",
			"remainder_qty":"Residual quantity",
			"max_qty":"Purchase Ceiling",
			"reverseAssociate":"Inversely correlated (This combination will be displayed simultaneously for the associated products when no combination is set)",
			"mainArea":"The product already exists in the main products area",
			"relatedArea":"The product already exists in the bundled products area",
			"holidayNotice":'Drag the product list on the right side to <b class="fc_red">"holiday-template products area"</b>',
			"seckillNotice":'Drag the product list on the right side to <b class="fc_red">"seckilling products area"</b>',
			"tuanNotice":'Drag the product list on the right side to <b class="fc_red">"group-buying products area"</b>',
			"relatedNotice":'Drag the product list on the right side to <b class="fc_red">"main products area"</b> and <b class="fc_red">"bundled products area"</b>',
			"beyondNumber":"Exceed the maximum limit number: ",
			"condition":"Consumption Conditions",
			"discount":"Discount",
			"money":"Money",
			"condition_tips":"This coupon can only be used when the shopping amount reaches the set value; there will be no restrictions on the usage conditions if you set 0",
			"discount_tips":"Please enter the percentage of discount; 20% is equivalent to 80% off, 80% is equivalent to 20% off",
			"money_tips":"Please enter the coupon code between 8 to 15 digits"
		},
		email:{
			"load_error":"Template data reading failed, please try again later!",
			"not_model":"No template is chosen!",
			"not_user":"No Member!",
			"not_content":"No Content!"
		},
		mta:{
			"traffic_time":['Last 30 days', 'Today', 'Yesterday', 'Last 7 days', 'Last 15 days'],
			"statistics_name":['Visitors', 'Pageviews']
		}
	},
	products:{
		'warning_number':'Purchase fewer than or more than the stock MOQ',
		'warning_MOQ':'Low from the MOQ',
		'warning_Max':'The maximum number of purchases %num%',
		'warning_stock':'Higher than the inventory %num%',
		'warning_attribute':'Please select parameters',
		'select_country':'--Please select your country--',
		'sign_in':'Please sign in first!',
		'free_shipping':'Free Shipping',
		'no_optional':'No optional',
	},
	cart:{
		'processing':'Processing, please wait...',
		'processing_str':'Processing',
		'checked_error':'Please select at least one item',
		'attribute_error':'There was an error in the product information, please remove this product and then re purchase.',
		'address_error':'Please enter your shipping address or choose one from your previously entered address. Ensure information, please click save after completed.',
		'shipping_error':'Please choose a delivery method.',
		'payment_error':'Please choose a payment method.',
		'product_error':'Your shopping cart is empty.',
		'low_error':'Your total product has not yet reached the lowest consumption value of the website',
		'stock_error':'Some products have insufficient inventory, you can not create an order correctly, adjust the purchase quantity.',
		'prod_stock_error':'This item is low in stock',
		'no_delivery':'Sorry! No delivery to this Country/Region!',
		'additem_0':'This product was successfully added to cart!',
		'additem_1':'<b class="FontColor">%num%</b> Item(s) in your cart. Subtotal: ',
		'return_shopping':'Return to Shopping',
		'proceed_checkout':'Proceed to Checkout',
		'arrival_info_0':'Has been successfully submitted to the business, the products cover will immediately notify the customer.',
		'arrival_info_1':'Please log in to apply for arrival notice.',
		'arrival_info_2':'This product has applied for the arrival notice!',
		'use_shipping_address':'Use This Shipping Address',
		'coupon_title':'Enter your coupon code',
		'coupon_tips':'The coupon code "<strong>%coupon%</strong>" is valid!<br /> Your discount is',
		'coupon_code':'Coupon Code',
		'apply':'Apply',
		'select_y_country':'Select you country',
		'remove':'Remove',
		'batch_remove_select':'Please select the item(s) you want to delete!',
		'batch_remove_success':'Product(s) deleted successfully!',
		'batch_remove_error':'Product(s) deletion failed!',
		'continue_str':'Continue Checkout',
		'total_amout':'Total Amout',
		'insurance':'Add Shipping Insurance to your order',
		'coupon_tips_to':'The coupon code %coupon% is invalid. It either does not exist, has not been activated yet, or has expired.',
		'coupon_tips_th':'The coupon code <strong></strong> is invalid. It either does not exist, has not been activated yet, or has expired.',
		'coupon_price_tips':"The total amount of the product is lower than the coupon's consumption conditions, the system automatically cancel the coupons now used.",
		'shipping_method_tips':'Please select a shipping method!',
		'cart_tips':'1 item added to cart',
		'plz_sel_para':'Please select parameters',
		'del_confirm':'Are you sure to delete it?',
		"paypal_tips":"Please select the same country as the PayPal account address information.",
	},
	orders:{
		'choose_payment':'Choose payment method',
		'order_total':'Order Total'
	},
	seckill:{
		'loading_tips':'There is no more products',
		'no_products':'Not match any products',
		'end':'Finished'
	},
	user:{
		'send_email_ture':'An email has been sent to you successfully. Please enter your email address and check the verification email.',
		'send_email_false':'Sorry, the email was sent in failure because of system problem. Please try again later.',
		'favorite_success':'This product Bookmarked!',
		'favorite_saved':'This product has been favorited!',
		'go_to_view':'Go to view',
		'order_cancel':'Are you sure you want to delete this pending order?',
		'sure':'Are you sure?',
		'delete_shipping':'Are you 100% sure you want to delete this address?',
		'reg_error':{
			'PleaseEnter':'Please enter your %field%.',
			'Email':'Please enter an email address.',
			'EmailFormat':"The email you've entered is invalid. Please check your email and try again.",
			'PWDConfirm':'Please re-enter your new password.',
			'PWDNotMatch':'Your passwords do not match, please try again.'
		},
		'address_tips':{
			'PleaseEnter':'Please enter your %field%.',
			'email':'Please enter your Email.',
			'email_format':'Email entered doesn\'t match with confirm Email value.',
			'firstname':'Please enter your first name.',
			'firstname_length':'Your First name must contain a minimum of 2 characters.',
			'lastname':'Please enter your last name.',
			'lastname_length':'Your First name must contain a minimum of 2 characters.',
			'address':'Please enter shipping address.',
			'address_length':'Your shipping address should be at least 5 characters long.',	
			'city':'Please enter your city.',
			'city_length':'Your city should be at least 3 characters long.',
			'country':'Please select your destination country/region.',
			'state':'Please select your state/province/region.',
			'taxcode':'Sorry, your %str% is required.',
			'taxcode_length':'Your %str% must contain a minimum of %taxlen% numbers.',
			'tariff':'Sorry, your %str% number is required.',
			'tariff_length':'Your %str% number must contain a minimum of 12 numbers.',
			'zip':'Please enter a ZIP / postal code.',
			'zip_length':'Your ZIP / postal code should be at least 4 digits long.',
			'phone':'Please enter your phone number.',
			'phone_format':'Please enter a valid phone number.',
			'phone_length':'Your phone number must be at least 7 digits.',
		}
	}
};